version: '3.8'

services:
  reservation-service:
    build: .
    container_name: reservation-service
    image: reservation-service:latest
    ports:
      - "9082:9082"
    networks:
      - reservation-network

networks:
  reservation-network:
    driver: bridge
