version: '3.8'

services:
  api-gateway:
    build: .
    container_name: api-gateway
    image: api-gateway:latest
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://user-service:9081
      - RESERVATION_SERVICE_URL=http://reservation-service:9082
      - NOTIFICATION_SERVICE_URL=http://notification-service:9083
    networks:
      - gateway-network
      - user-network
      - reservation-network
      - notification-network

networks:
  gateway-network:
    driver: bridge
  user-network:
    driver: bridge
  reservation-network:
    driver: bridge
  notification-network:
    driver: bridge

